-- Auto-generated from roster spreadsheet. Safe to re-run (upserts on name).
insert into drivers
  (car_number, name, status_id, class_id, team_id, is_rookie, car,
   appearances, starts, seasons_count, penalty_points, penalty_points_max)
values
  (0, 'Jielin Kuo', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Penguin Mafia'), false, NULL, 11, 14, 3, 4, 11),
  (1, 'Michael Polasek', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'Yellow Flag Motorsport'), false, 'Honda Civic', 75, 108, 8, 4, 11),
  (2, 'John Daniels3', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'T0 Racing Summit'), false, 'Hyundai Elantra', 47, 65, 4, 6, 11),
  (3, 'Kurt Smith', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Bee 4 Deez'), false, 'Hyundai Veloster', 64, 102, 11, 7, 11),
  (4, 'Logan McKinzie', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'PENNZOIL Super Touring'), false, 'Audi RS 3', 208, 337, 17, 0, 11),
  (6, 'Mike de Almeida', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Yellow Flag Motorsport'), false, NULL, 106, 150, 11, 0, 11),
  (7, 'Jacob Simmons7', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Alpha'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (8, 'Matt Girardi', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (9, 'Joshua Bibb', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Waifu No Laifu'), true, NULL, 1, 1, 1, 0, 11),
  (10, 'Qeex Mak', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (11, 'Tim Laws', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Gamma'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (12, 'Matthew Meilleur', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'SyartG'), false, NULL, 61, 85, 7, 2, 11),
  (13, 'Fleet Smith', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Bee 4 Deez'), false, NULL, 25, 35, 4, 2, 11),
  (14, 'Robert Abrams', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 103, 182, 14, 0, 11),
  (15, 'David Thomas15', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'CHASE Sim Racing'), false, NULL, 45, 63, 4, 0, 11),
  (17, 'Agust Blondal', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 89, 162, 11, 0, 11),
  (18, 'Francois Shink', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'Curb Your Enthusiasm Autosport'), false, NULL, 188, 307, 17, 5, 11),
  (19, 'James D Carr', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Breakfast 4 Dinner'), false, NULL, 106, 167, 12, 0, 11),
  (20, 'Trenton Kramer', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 7, 11, 3, 0, 11),
  (21, 'Kyle Trost', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'T0 Racing Ascent'), false, NULL, 35, 48, 3, 2, 11),
  (22, 'Adrian Fedorowski', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = '212 Racing'), false, NULL, 54, 82, 11, 0, 11),
  (23, 'Dan McFarlane', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Sim Racing Grid'), false, NULL, 87, 124, 12, 1.5, 11),
  (24, 'Kevin Johnson21', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 15, 21, 5, 0, 11),
  (25, 'Gareth McAlister', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'You Matter Motorsport'), false, NULL, 48, 69, 6, 0, 11),
  (26, 'Angel Bonilla Soto', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Penguin Mafia'), false, NULL, 10, 14, 3, 3, 11),
  (27, 'Damon Mitchell', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Croc Promotions'), false, NULL, 115, 165, 12, 0, 11),
  (29, 'Cooper Akers', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'PENNZOIL Super Touring'), false, NULL, 55, 80, 7, 0, 11),
  (30, 'Gonzalo Fabi', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Alpha'), NULL, false, NULL, 15, 22, 3, 0, 11),
  (31, 'Pierce Sonderup', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Gamma'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (32, 'Shaun Gurd', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Gasparilla Motorsport'), false, NULL, 20, 35, 3, 0, 11),
  (33, 'Ryan Small4', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 2, 3, 2, 0, 11),
  (34, 'Bryan Inagaki', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 11, 16, 2, 0, 11),
  (35, 'David Bauer2', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 114, 177, 12, 0, 11),
  (36, 'Yuanxi Lin', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 9, 13, 1, 0, 11),
  (37, 'Cameron Demunck', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (38, 'Aaron La', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 67, 113, 16, 0, 11),
  (39, 'Ronald Methot', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Gasparilla Motorsport'), false, NULL, 20, 35, 2, 0, 11),
  (41, 'Cory Lobner', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 41, 54, 5, 2, 11),
  (43, 'Jared Dixon', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 2, 4, 2, 0, 11),
  (44, 'Jake Puzio', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (48, 'John Agudelo', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (49, 'Jay Caullay', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Gamma'), NULL, true, NULL, 1, 2, 1, 0, 11),
  (50, 'Andrew Cossick', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 5, 7, 1, 0, 11),
  (51, 'Ian Bertolucci', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Sim Racing Grid'), false, NULL, 76, 107, 11, 3, 11),
  (52, 'Ryan Kish', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (55, 'Connor Accettella', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 111, 170, 13, 0, 11),
  (56, 'Angel Resendiz', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (57, 'Lewis Gilbert2', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Gator Racing'), false, NULL, 52, 73, 6, 4, 11),
  (58, 'Major Moncivais', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'T0 Racing Summit'), false, NULL, 22, 30, 2, 0, 11),
  (62, 'Matthew Coley2', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (64, 'Shawn Harvey', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (66, 'Nolan Pesola', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 2, 1, 0, 11),
  (67, 'Christopher A Young', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 6, 9, 2, 0, 11),
  (69, 'Tianyi Chang', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 21, 29, 4, 0, 11),
  (71, 'Joseph Heath', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 8, 12, 1, 0, 11),
  (72, 'Zachary Liebold', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'PENNZOIL Super Touring'), false, NULL, 36, 52, 4, 1, 11),
  (73, 'Micah Hendricks', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'Croc Promotions'), false, NULL, 151, 226, 13, 2, 11),
  (75, 'Logan Watern', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 2, 1, 0, 11),
  (76, 'Zac Hudacko', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'T0 Racing Ascent'), false, NULL, 20, 28, 2, 0, 11),
  (77, 'Jon Lauzon', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Beaver & Deez'), false, NULL, 178, 289, 17, 1, 11),
  (78, 'Nicholas Sudik', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 5, 6, 1, 0, 11),
  (79, 'Benjamin M Andrews', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (80, 'Wojciech Swirydowicz', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'Beaver & Deez'), false, NULL, 77, 130, 12, 3, 11),
  (82, 'Jonathan Bradford', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 6, 9, 1, 0, 11),
  (83, 'Mark Darnell', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Gator Racing'), false, NULL, 152, 242, 16, 0, 11),
  (84, 'Justin T Rhodes', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 51, 88, 6, 0, 11),
  (85, 'Chris Macdonald5', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Croc Promotions'), false, NULL, 49, 69, 5, 2, 11),
  (87, 'Marco Mangano', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 2, 3, 1, 0, 11),
  (89, 'Mitchell Richtmyre', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'You Matter Motorsport'), false, NULL, 57, 82, 6, 0, 11),
  (91, 'Tyler Langenberg', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 2, 1, 0, 11),
  (92, 'Colten Hopsecker', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (94, 'Stephen Lichota', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 7, 12, 4, 0, 11),
  (95, 'Tim Gardinier', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (96, 'Raymond Tieu', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'Beaver & Deez'), false, NULL, 109, 157, 11, 0, 11),
  (97, 'Billee van Beek', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 3, 4, 1, 0, 11),
  (99, 'Eli Sasak', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 3, 4, 2, 0, 11),
  (101, 'Kyle Murray2', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'SyartG'), false, NULL, 63, 90, 7, 0, 11),
  (104, 'Zachary Sawczuk', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (110, 'Taylor Bookout', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (112, 'Ryan McKie', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (114, 'Mat Gatter', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (117, 'Zack Saunders', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 4, 6, 2, 0, 11),
  (119, 'Fouad Al-Rijleh', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'SyartG'), false, NULL, 83, 118, 8, 4, 11),
  (127, 'Tim Driscoll', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 2, 3, 1, 0, 11),
  (128, 'Manuel Saralegui', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Alpha'), NULL, false, NULL, 8, 12, 2, 0, 11),
  (131, 'Jack Anthony Brown', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Alpha'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (132, 'Thomas Pfannkoch', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 3, 4, 2, 0, 11),
  (133, 'Nick Beyda', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 18, 26, 6, 0, 11),
  (137, 'Edward Gorman', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 37, 55, 6, 0, 11),
  (150, 'Aiden Cale', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Alpha'), NULL, true, NULL, 1, 2, 1, 0, 11),
  (151, 'Jordon Bachmeyer', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Alpha'), NULL, true, NULL, 4, 7, 2, 0, 11),
  (157, 'Christian S. Ost', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Problem Child Motorsport'), false, NULL, 46, 67, 6, 0, 11),
  (167, 'Jeromy Barber', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'You Matter Motorsport'), false, NULL, 35, 48, 5, 0, 11),
  (187, 'Evan M Clavijo', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Sim Racing Grid'), false, NULL, 70, 100, 8, 6, 11),
  (197, 'James Costlow', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (198, 'Emma Sinclair', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (199, 'Michael Bowman3', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Waifu No Laifu'), true, NULL, 2, 2, 1, 0, 11),
  (210, 'Tyler K Stuckey', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 9, 15, 4, 0, 11),
  (212, 'Nathan Hemperley', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Waifu No Laifu'), true, NULL, 2, 2, 1, 0, 11),
  (216, 'Derek Putnam', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (217, 'Jason Breen', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 24, 35, 4, 0, 11),
  (223, 'Joshua Grosso', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Gamma'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (228, 'Marcel Thomas', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 17, 24, 2, 0, 11),
  (230, 'Michael Zepp', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 21, 33, 6, 0, 11),
  (250, 'Nicolas Szwedska', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Szwedska Racing'), false, NULL, 8, 11, 1, 1, 11),
  (263, 'Tyler J Potts', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 3, 3, 1, 0, 11),
  (303, 'Arup Mistry', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (311, 'Eric Taverna', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (312, 'Christopher Ondera', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Junk in the Trunk e-lectronica''s'), false, NULL, 5, 7, 1, 1.5, 11),
  (327, 'Michael Stoegbauer', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Alpha'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (333, 'Austin Dunbar', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Problem Child Motorsport'), false, NULL, 27, 38, 4, 0, 11),
  (350, 'Jarrad Wakefield', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 2, 3, 2, 0, 11),
  (355, 'Jeff Cartwright', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (388, 'Jonathan Lantin', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Junk in the Trunk e-lectronica''s'), true, NULL, 2, 3, 1, 0, 11),
  (421, 'Kyle Flannery', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Gasparilla Motorsport'), false, NULL, 7, 10, 1, 0, 11),
  (451, 'Ian Bost', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (490, 'Matthew Rzepka', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Curb Your Enthusiasm Autosport'), false, NULL, 164, 255, 15, 0, 11),
  (595, 'Daniel L Mills', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Alpha'), (select id from teams where name = 'Curb Your Enthusiasm Autosport'), false, NULL, 5, 8, 2, 0, 11),
  (603, 'Matthew Clough2', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (611, 'Daniel M Bond', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 4, 5, 1, 0, 11),
  (621, 'J.B. DeJeu', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 77, 124, 10, 0, 11),
  (654, 'Zachary Bowman', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), (select id from teams where name = 'Yellow Flag Motorsport'), false, NULL, 57, 79, 7, 5, 11),
  (661, 'Jason C Lin', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'Gator Racing'), false, NULL, 93, 132, 9, 9, 11),
  (666, 'Patrick Rich', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 5, 8, 2, 0, 11),
  (686, 'Joe Varvel', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 5, 7, 1, 0, 11),
  (710, 'Daniel Cedeno', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 84, 145, 12, 0, 11),
  (767, 'Tyler J Long', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'T0 Racing Ascent'), false, NULL, 33, 46, 3, 0, 11),
  (789, 'Eric Statzer', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 79, 133, 9, 0, 11),
  (827, 'Jacob Whalley', (select id from driver_statuses where name = 'Veteran'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 51, 87, 7, 0, 11),
  (881, 'Kirk Lane', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 33, 52, 5, 0, 11),
  (900, 'Noah Nahmiach', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 8, 10, 2, 0, 11),
  (911, 'Anthony Harrison', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Gamma'), NULL, false, NULL, 32, 44, 4, 0, 11),
  (919, 'Spencer Clarke', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 60, 84, 8, 0, 11),
  (942, 'Logan Warfield', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 5, 7, 3, 0, 11),
  (950, 'Rodger Schank', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (952, 'Brian Sobb', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'CHASE Sim Racing'), false, NULL, 69, 101, 7, 0, 11),
  (956, 'Agustín Fernandez', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Alpha'), NULL, false, NULL, 18, 26, 6, 0, 11),
  (958, 'Daniel Carlosama', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (959, 'Dave Hernandez', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 3, 4, 3, 0, 11),
  (960, 'Mark Bouley2', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 6, 8, 1, 0, 11),
  (967, 'Javi Sierra', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 4, 6, 1, 0, 11),
  (977, 'Daniel Beckett', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 0, 0, 0, 0, 11),
  (994, 'Gustavo Diniz', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 2, 3, 1, 0, 11),
  (995, 'Jacob D Wilson', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 1, 2, 1, 0, 11),
  (996, 'Robert Wrzesinski', (select id from driver_statuses where name = 'New'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 0, 0, 0, 0, 11),
  (997, 'Victor Vallee', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, true, NULL, 2, 2, 1, 0, 11),
  (998, 'Joe Camilleri', (select id from driver_statuses where name = 'Inactive'), (select id from driver_classes where name = 'Delta'), NULL, false, NULL, 20, 34, 7, 0, 11),
  (NULL, 'Alexander Gonzalez-Greene', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Gamma'), NULL, true, NULL, 1, 1, 1, 0, 11),
  (999, 'Jess Rakowski', (select id from driver_statuses where name = 'Active'), (select id from driver_classes where name = 'Delta'), (select id from teams where name = 'T0 Racing Summit'), false, NULL, 36, 51, 7, 5, 11)
on conflict (name) do update set
  car_number = excluded.car_number,
  status_id = excluded.status_id,
  class_id = excluded.class_id,
  team_id = excluded.team_id,
  is_rookie = excluded.is_rookie,
  car = excluded.car,
  appearances = excluded.appearances,
  starts = excluded.starts,
  seasons_count = excluded.seasons_count,
  penalty_points = excluded.penalty_points,
  penalty_points_max = excluded.penalty_points_max;
